name: yxcvbn

on:
  pull_request:
    branches:
      - master
  push:


jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt
    

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --verbose

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace
    
      - name: Install cargo-audit
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-audit
    
      - name: Audit
        uses: actions-rs/cargo@v1
        with:
          command: audit

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build (default features)
        run: cargo build --tests --benches

      - name: Run tests (default features)
        run: cargo test

      - name: Build (default features)
        run: cargo build --tests --benches

      - name: Run tests (all features)
        run: cargo test --all-features

      - name: Generate docs
        run: cargo doc --all-features --no-deps

